// Generated by npm run sync:obsidian. Do not edit by hand.
export const obsidianNotes = [
  {
    "category": "Watches",
    "title": "My Watch Collection",
    "excerpt": "My current watch collection, purchase priorities, wishlist, and ultimate grail watch.",
    "date": "20 Aug 2026",
    "read": "3 min",
    "slug": "my-watch-collection"
  }
] as const;
