// Generated by npm run sync:obsidian. Do not edit by hand.
export const obsidianWatches = [
  {
    "name": "Swatch Irony Automatic Body & Soul",
    "brand": "Swatch",
    "status": "Collection",
    "detail": "Automatic mechanical movement · ~37 mm",
    "reference": "YAS100G",
    "accent": "#aab4bb",
    "dial": "#14191d"
  },
  {
    "name": "Swatch Irony Big Pergamena",
    "brand": "Swatch",
    "status": "Collection",
    "detail": "Quartz · ~37.4 mm",
    "reference": "YGS708A/B",
    "accent": "#929da3",
    "dial": "#d7d1bd"
  },
  {
    "name": "Festina Timeless Chronograph",
    "brand": "Festina",
    "status": "Collection",
    "detail": "Quartz chronograph · 41.5 mm",
    "reference": "F20285/A",
    "accent": "#7f8b92",
    "dial": "#17191c"
  },
  {
    "name": "Traska Venturer GMT",
    "brand": "Traska",
    "status": "Wishlist",
    "detail": "Miyota 9075 automatic · 38.5 mm",
    "reference": "Wishlist",
    "accent": "#8ba4a9",
    "dial": "#183640"
  },
  {
    "name": "Certina DS Action Diver 38",
    "brand": "Certina",
    "status": "Wishlist",
    "detail": "Powermatic 80 automatic · 38 mm",
    "reference": "Wishlist",
    "accent": "#8f9caa",
    "dial": "#122d48"
  },
  {
    "name": "Hamilton Khaki Field Mechanical 38",
    "brand": "Hamilton",
    "status": "Wishlist",
    "detail": "H-50 manual-wind · 38 mm",
    "reference": "Wishlist",
    "accent": "#a79a86",
    "dial": "#202018"
  },
  {
    "name": "Baltic MR Classic",
    "brand": "Baltic",
    "status": "Wishlist",
    "detail": "Automatic micro-rotor",
    "reference": "Wishlist",
    "accent": "#82949c",
    "dial": "#25363d"
  },
  {
    "name": "Tissot Gentleman Powermatic 80",
    "brand": "Tissot",
    "status": "Wishlist",
    "detail": "Swiss automatic",
    "reference": "Wishlist",
    "accent": "#9aa2a6",
    "dial": "#1e2c3f"
  },
  {
    "name": "Audemars Piguet Code 11.59 Starwheel",
    "brand": "Audemars Piguet",
    "status": "Dream",
    "detail": "Automatic",
    "reference": "Grail",
    "accent": "#b0a590",
    "dial": "#30281c"
  }
] as const;
